<template>
  <aside class="w-60 h-full">
    <el-menu :default-active="$route.path" :router="false" unique-opened>
      <AsideItem v-for="item in menuList" :key="item.code" :item="item" />
    </el-menu>
  </aside>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import AsideItem from '@/components/CommonAside/AsideItem.vue'
import type { MenuItem } from './menu'

const menuList = ref<MenuItem[]>([
  {
    code: 'permission.menu.home',
    parentCode: null,
    children: null,
    name: '首页',
    type: 2,
    sort: 0,
    subType: 201,
    iconUrl: 'icon/home.png',
    router: '/home',
    enable: true,
    description: null,
    accessCode: null,
  },
  {
    code: 'permission.menu.merchant',
    parentCode: null,
    children: [
      {
        code: 'permission.menu.merchant.account',
        parentCode: 'permission.menu.merchant',
        children: [],
        name: '账户管理',
        type: 2,
        sort: 0,
        subType: 201,
        iconUrl: '',
        router: '/merchant/account-list',
        enable: true,
        description: null,
        accessCode: 'MERCHANT_ACCOUNT_MANAGEMENT',
      },
      {
        code: 'permission.menu.merchant.company',
        parentCode: 'permission.menu.merchant',
        children: [],
        name: '企业管理',
        type: 2,
        sort: 0,
        subType: 201,
        iconUrl: '',
        router: '/merchant/company-list',
        enable: true,
        description: null,
        accessCode: 'MERCHANT_COMPANY_MANAGEMENT',
      },
      {
        code: 'permission.menu.merchant.personal',
        parentCode: 'permission.menu.merchant',
        children: [],
        name: '个人管理',
        type: 2,
        sort: 0,
        subType: 201,
        iconUrl: '',
        router: '/merchant/personal-list',
        enable: true,
        description: null,
        accessCode: 'MERCHANT_PERSONAL_MANAGEMENT',
      },
    ],
    name: '商户管理',
    type: 2,
    sort: 0,
    subType: 201,
    iconUrl: 'icon/merchant.png',
    router: '',
    enable: true,
    description: null,
    accessCode: 'MERCHANT_MANAGEMENT',
  },
  {
    code: 'permission.menu.perssion',
    parentCode: null,
    children: [
      {
        code: 'permission.menu.perssion.account',
        parentCode: 'permission.menu.perssion',
        children: [],
        name: '账号管理',
        type: 2,
        sort: 0,
        subType: 201,
        iconUrl: '',
        router: '/permission/account-list',
        enable: true,
        description: null,
        accessCode: 'ACCOUNT_MANAGEMENT',
      },
      {
        code: 'permission.menu.perssion.role',
        parentCode: 'permission.menu.perssion',
        children: [],
        name: '角色管理',
        type: 2,
        sort: 0,
        subType: 201,
        iconUrl: '',
        router: '/permission/role-list',
        enable: true,
        description: null,
        accessCode: 'ROLE_MANAGEMENT',
      },
    ],
    name: '权限管理',
    type: 2,
    sort: 0,
    subType: 201,
    iconUrl: 'icon/permission.png',
    router: '',
    enable: true,
    description: null,
    accessCode: 'PERMISSION_MANAGEMENT',
  },
  {
    code: 'permission.menu.ruleEngine',
    parentCode: null,
    children: [
      {
        code: 'permission.menu.ruleEngine.ruleManager',
        parentCode: 'permission.menu.ruleEngine',
        children: [],
        name: '规则管理',
        type: 2,
        sort: 0,
        subType: 201,
        iconUrl: '',
        router: '/rule-engine/rule-management-list',
        enable: true,
        description: null,
        accessCode: '',
      },
      {
        code: 'permission.menu.ruleEngine.ruleType',
        parentCode: 'permission.menu.ruleEngine',
        children: [],
        name: '规则类型',
        type: 2,
        sort: 0,
        subType: 201,
        iconUrl: '',
        router: '/rule-engine/rule-type-list',
        enable: true,
        description: null,
        accessCode: '',
      },
    ],
    name: '规则引擎',
    type: 2,
    sort: 0,
    subType: 201,
    iconUrl: 'icon/rule-engine.png',
    router: '',
    enable: true,
    description: null,
    accessCode: '',
  },
  {
    code: 'permission.menu.trade',
    parentCode: null,
    children: [],
    name: '交易认证',
    type: 2,
    sort: 0,
    subType: 201,
    iconUrl: 'icon/trade-auth.png',
    router: '/trading/authentication-list',
    enable: true,
    description: null,
    accessCode: 'TRADING_AUTH',
  },
  {
    code: 'permission.menu.check',
    parentCode: null,
    children: [],
    name: '抽查管理',
    type: 2,
    sort: 1,
    subType: 201,
    iconUrl: 'icon/spot-check.png',
    router: '/trading/check-manage-list',
    enable: true,
    description: null,
    accessCode: '',
  },
  {
    code: 'permission.menu.audit',
    parentCode: null,
    children: [
      {
        code: 'permission.menu.audit.noAudit',
        parentCode: 'permission.menu.audit',
        children: [],
        name: '待审核列表',
        type: 2,
        sort: 0,
        subType: 201,
        iconUrl: '',
        router: '/manual-check/pending-list',
        enable: true,
        description: null,
        accessCode: '',
      },
      {
        code: 'permission.menu.audit.history',
        parentCode: 'permission.menu.audit',
        children: [],
        name: '已审核列表',
        type: 2,
        sort: 1,
        subType: 201,
        iconUrl: '',
        router: '/manual-check/checked-list',
        enable: true,
        description: null,
        accessCode: '',
      },
    ],
    name: '审核管理',
    type: 2,
    sort: 2,
    subType: 201,
    iconUrl: 'icon/manual-check.png',
    router: '',
    enable: true,
    description: null,
    accessCode: '',
  },
  {
    code: 'permission.menu.merchant.newItem1',
    parentCode: 'permission.menu.merchant',
    children: [],
    name: '新项目1',
    type: 2,
    sort: 0,
    subType: 201,
    router: '/merchant/new-item1',
    enable: true,
    iconUrl: 'icon/home.png',
    description: null,
    accessCode: 'MERCHANT_NEW_ITEM1',
  },
  {
    code: 'permission.menu.merchant.newItem2',
    parentCode: 'permission.menu.merchant',
    children: [],
    name: '新项目2',
    type: 2,
    sort: 0,
    subType: 201,
    iconUrl: 'icon/home.png',
    router: '/merchant/new-item2',
    enable: true,
    description: null,
    accessCode: 'MERCHANT_NEW_ITEM2',
  },
  {
    code: 'permission.menu.merchant.newItem3',
    parentCode: 'permission.menu.merchant',
    children: [],
    name: '新项目1',
    type: 2,
    sort: 0,
    subType: 201,
    router: '/merchant/new-item1',
    enable: true,
    iconUrl: 'icon/home.png',
    description: null,
    accessCode: 'MERCHANT_NEW_ITEM1',
  },
  {
    code: 'permission.menu.merchant.newItem4',
    parentCode: 'permission.menu.merchant',
    children: [],
    name: '新项目2',
    type: 2,
    sort: 0,
    subType: 201,
    iconUrl: 'icon/home.png',
    router: '/merchant/new-item2',
    enable: true,
    description: null,
    accessCode: 'MERCHANT_NEW_ITEM2',
  },
])
</script>

<style scoped lang="scss">
@import './AsideComponent.scss';
</style>
./menu
